# Generated by Django 3.1.7 on 2021-03-29 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_auto_20210330_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='created_at',
            field=models.DateTimeField(verbose_name='%m/%d/%Y %H:%M:%S'),
        ),
        migrations.AlterField(
            model_name='member',
            name='updated_at',
            field=models.DateTimeField(verbose_name='%m/%d/%Y %H:%M:%S'),
        ),
    ]
