# Generated by Django 3.1.7 on 2021-03-29 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0006_auto_20210330_0230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='date',
            new_name='event_date',
        ),
    ]
